name: Send Request PR Review

on:
  pull_request:
    types: [review_requested]

jobs:
  send:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send Request PR Review
        uses: ./
        with:
          slack-url: ${{ secrets.SLACK_URL }}
